package sun.util.resources.ext;

import java.util.ListResourceBundle;

public final class CurrencyNames_fr extends sun.util.resources.LocaleNamesBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "adp", "peseta andorrane" },
            { "aed", "dirham des \u00C9mirats arabes unis" },
            { "afa", "afghani (1927\u20132002)" },
            { "afn", "afghani" },
            { "all", "lek albanais" },
            { "amd", "dram arm\u00E9nien" },
            { "ang", "florin antillais" },
            { "aoa", "kwanza angolais" },
            { "ars", "peso argentin" },
            { "ats", "schilling autrichien" },
            { "aud", "dollar australien" },
            { "awg", "florin arubais" },
            { "azm", "manat az\u00E9ri (1993-2006)" },
            { "azn", "manat az\u00E9ri" },
            { "bam", "mark convertible bosniaque" },
            { "bbd", "dollar barbadien" },
            { "bdt", "taka bangladeshi" },
            { "bef", "franc belge" },
            { "bgl", "lev bulgare (1962\u20131999)" },
            { "bgn", "nouveau lev bulgare" },
            { "bhd", "dinar bahre\u00EFni" },
            { "bif", "franc burundais" },
            { "bmd", "dollar bermudien" },
            { "bnd", "dollar brun\u00E9ien" },
            { "bob", "boliviano" },
            { "bov", "mvdol bolivien" },
            { "brl", "r\u00E9al br\u00E9silien" },
            { "bsd", "dollar baham\u00E9en" },
            { "btn", "ngultrum bouthanais" },
            { "bwp", "pula botswanais" },
            { "byb", "nouveau rouble bi\u00E9lorusse (1994-1999)" },
            { "byr", "rouble bi\u00E9lorusse" },
            { "bzd", "dollar b\u00E9liz\u00E9en" },
            { "cad", "dollar canadien" },
            { "cdf", "franc congolais" },
            { "chf", "franc suisse" },
            { "clf", "unit\u00E9 d\u2019investissement chilienne" },
            { "clp", "peso chilien" },
            { "cny", "yuan renminbi chinois" },
            { "cop", "peso colombien" },
            { "crc", "col\u00F3n costaricain" },
            { "csd", "dinar serbo-mont\u00E9n\u00E9grin" },
            { "cuc", "peso cubain convertible" },
            { "cup", "peso cubain" },
            { "cve", "escudo capverdien" },
            { "cyp", "livre chypriote" },
            { "czk", "couronne tch\u00E8que" },
            { "dem", "mark allemand" },
            { "djf", "franc djiboutien" },
            { "dkk", "couronne danoise" },
            { "dop", "peso dominicain" },
            { "dzd", "dinar alg\u00E9rien" },
            { "eek", "couronne estonienne" },
            { "egp", "livre \u00E9gyptienne" },
            { "ern", "nafka \u00E9rythr\u00E9en" },
            { "esp", "peseta espagnole" },
            { "etb", "birr \u00E9thiopien" },
            { "eur", "euro" },
            { "fim", "mark finlandais" },
            { "fjd", "dollar fidjien" },
            { "fkp", "livre des Falkland" },
            { "frf", "franc fran\u00E7ais" },
            { "gbp", "livre sterling" },
            { "gel", "lari g\u00E9orgien" },
            { "ghc", "c\u00E9di" },
            { "ghs", "c\u00E9di ghan\u00E9en" },
            { "gip", "livre de Gibraltar" },
            { "gmd", "dalasi gambien" },
            { "gnf", "franc guin\u00E9en" },
            { "grd", "drachme grecque" },
            { "gtq", "quetzal guat\u00E9malt\u00E8que" },
            { "gwp", "peso bissau-guin\u00E9en" },
            { "gyd", "dollar du Guyana" },
            { "hkd", "dollar de Hong Kong" },
            { "hnl", "lempira hondurien" },
            { "hrk", "kuna croate" },
            { "htg", "gourde ha\u00EFtienne" },
            { "huf", "forint hongrois" },
            { "idr", "roupie indon\u00E9sienne" },
            { "iep", "livre irlandaise" },
            { "ils", "nouveau shekel isra\u00E9lien" },
            { "inr", "roupie indienne" },
            { "iqd", "dinar irakien" },
            { "irr", "rial iranien" },
            { "isk", "couronne islandaise" },
            { "itl", "lire italienne" },
            { "jmd", "dollar jama\u00EFcain" },
            { "jod", "dinar jordanien" },
            { "jpy", "yen japonais" },
            { "kes", "shilling k\u00E9nyan" },
            { "kgs", "som kirghize" },
            { "khr", "riel cambodgien" },
            { "kmf", "franc comorien" },
            { "kpw", "won nord-cor\u00E9en" },
            { "krw", "won sud-cor\u00E9en" },
            { "kwd", "dinar kowe\u00EFtien" },
            { "kyd", "dollar des \u00EEles Ca\u00EFmanes" },
            { "kzt", "tenge kazakh" },
            { "lak", "kip loatien" },
            { "lbp", "livre libanaise" },
            { "lkr", "roupie srilankaise" },
            { "lrd", "dollar lib\u00E9rien" },
            { "lsl", "loti lesothan" },
            { "ltl", "litas lituanien" },
            { "luf", "franc luxembourgeois" },
            { "lvl", "lats letton" },
            { "lyd", "dinar lybien" },
            { "mad", "dirham marocain" },
            { "mdl", "leu moldave" },
            { "mga", "ariary malgache" },
            { "mgf", "franc malgache" },
            { "mkd", "denar mac\u00E9donien" },
            { "mmk", "kyat myanmarais" },
            { "mnt", "tugrik mongol" },
            { "mop", "pataca macanaise" },
            { "mro", "ouguiya mauritanien" },
            { "mtl", "lire maltaise" },
            { "mur", "roupie mauricienne" },
            { "mvr", "rufiyaa maldivienne" },
            { "mwk", "kwacha malawite" },
            { "mxn", "peso mexicain" },
            { "mxv", "unit\u00E9 de conversion mexicaine (UDI)" },
            { "myr", "ringgit malais" },
            { "mzm", "m\u00E9tical" },
            { "mzn", "metical mozambicain" },
            { "nad", "dollar namibien" },
            { "ngn", "naira nig\u00E9rian" },
            { "nio", "c\u00F3rdoba oro nicaraguayen" },
            { "nlg", "florin n\u00E9erlandais" },
            { "nok", "couronne norv\u00E9gienne" },
            { "npr", "roupie n\u00E9palaise" },
            { "nzd", "dollar n\u00E9o-z\u00E9landais" },
            { "omr", "rial omani" },
            { "pab", "balboa panam\u00E9en" },
            { "pen", "nouveau sol p\u00E9ruvien" },
            { "pgk", "kina papouan-n\u00E9o-guin\u00E9en" },
            { "php", "peso philippin" },
            { "pkr", "roupie pakistanaise" },
            { "pln", "zloty polonais" },
            { "pte", "escudo portugais" },
            { "pyg", "guaran\u00ED paraguayen" },
            { "qar", "rial qatari" },
            { "rol", "ancien leu roumain" },
            { "ron", "leu roumain" },
            { "rsd", "dinar serbe" },
            { "rub", "rouble russe" },
            { "rur", "rouble russe (1991\u20131998)" },
            { "rwf", "franc rwandais" },
            { "sar", "rial saoudien" },
            { "sbd", "dollar des \u00EEles Salomon" },
            { "scr", "roupie des Seychelles" },
            { "sdd", "dinar soudanais" },
            { "sdg", "livre soudanaise" },
            { "sek", "couronne su\u00E9doise" },
            { "sgd", "dollar de Singapour" },
            { "shp", "livre de Sainte-H\u00E9l\u00E8ne" },
            { "sit", "tolar slov\u00E8ne" },
            { "skk", "couronne slovaque" },
            { "sll", "leone sierra-l\u00E9onais" },
            { "sos", "shilling somalien" },
            { "srd", "dollar surinamais" },
            { "srg", "florin surinamais" },
            { "std", "dobra santom\u00E9en" },
            { "svc", "col\u00F3n salvadorien" },
            { "syp", "livre syrienne" },
            { "szl", "lilangeni swazi" },
            { "thb", "baht tha\u00EFlandais" },
            { "tjs", "somoni tadjik" },
            { "tmm", "manat turkm\u00E8ne" },
            { "tmt", "nouveau manat turkm\u00E8ne" },
            { "tnd", "dinar tunisien" },
            { "top", "pa\u2019anga tongan" },
            { "tpe", "escudo timorais" },
            { "trl", "livre turque" },
            { "try", "nouvelle livre turque" },
            { "ttd", "dollar trinidadien" },
            { "twd", "nouveau dollar ta\u00EFwanais" },
            { "tzs", "shilling tanzanien" },
            { "uah", "hryvnia ukrainienne" },
            { "ugx", "shilling ougandais" },
            { "usd", "dollar des \u00C9tats-Unis" },
            { "usn", "dollar des Etats-Unis (jour suivant)" },
            { "uss", "dollar des Etats-Unis (jour m\u00EAme)" },
            { "uyu", "peso uruguayen" },
            { "uzs", "sum ouzbek" },
            { "veb", "bolivar" },
            { "vef", "bolivar fuerte v\u00E9n\u00E9zu\u00E9lien" },
            { "vnd", "d\u00F4ng vietnamien" },
            { "vuv", "vatu vanuatuan" },
            { "wst", "tala samoan" },
            { "xaf", "franc CFA (BEAC)" },
            { "xag", "argent" },
            { "xau", "or" },
            { "xba", "unit\u00E9 europ\u00E9enne compos\u00E9e" },
            { "xbb", "unit\u00E9 mon\u00E9taire europ\u00E9enne" },
            { "xbc", "unit\u00E9 de compte europ\u00E9enne (XBC)" },
            { "xbd", "unit\u00E9 de compte europ\u00E9enne (XBD)" },
            { "xcd", "dollar des Cara\u00EFbes orientales" },
            { "xdr", "droit de tirage sp\u00E9cial" },
            { "xfo", "franc or" },
            { "xfu", "franc UIC" },
            { "xof", "franc CFA (BCEAO)" },
            { "xpd", "palladium" },
            { "xpf", "franc CFP" },
            { "xpt", "platine" },
            { "xts", "(devise de test)" },
            { "xxx", "devise inconnue ou non valide" },
            { "yer", "rial y\u00E9m\u00E9nite" },
            { "yum", "dinar yougoslave Noviy" },
            { "zar", "rand sud-africain" },
            { "zmk", "kwacha zambien" },
            { "zwd", "dollar zimbabw\u00E9en" },
        };
    }
}
