package sun.util.resources.ext;

import java.util.ListResourceBundle;

public final class CurrencyNames_pt extends sun.util.resources.LocaleNamesBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "adp", "Peseta de Andorra" },
            { "aed", "Dir\u00E9m dos Emirados \u00C1rabes Unidos" },
            { "afa", "Afegane (1927-2002)" },
            { "afn", "Afegane" },
            { "all", "Lek Alban\u00EAs" },
            { "amd", "Dram arm\u00EAnio" },
            { "ang", "Guilder das Antilhas Holandesas" },
            { "aoa", "Cuanza angolano" },
            { "ars", "Peso argentino" },
            { "ats", "Xelim austr\u00EDaco" },
            { "aud", "D\u00F3lar australiano" },
            { "awg", "Guilder de Aruba" },
            { "azm", "Manat azerbaijano" },
            { "azn", "Manat do Azerbaij\u00E3o" },
            { "bam", "Marco b\u00F3snio-herzegovino convers\u00EDvel" },
            { "bbd", "D\u00F3lar de Barbados" },
            { "bdt", "Taka de Bangladesh" },
            { "bef", "Franco belga" },
            { "bgl", "Lev forte b\u00FAlgaro" },
            { "bgn", "Lev novo b\u00FAlgaro" },
            { "bhd", "Dinar bareinita" },
            { "bif", "Franco do Burundi" },
            { "bmd", "D\u00F3lar das Bermudas" },
            { "bnd", "D\u00F3lar do Brunei" },
            { "bob", "Boliviano" },
            { "bov", "Mvdol boliviano" },
            { "brl", "Real brasileiro" },
            { "bsd", "D\u00F3lar das Bahamas" },
            { "btn", "Ngultrum do But\u00E3o" },
            { "bwp", "Pula botsuanesa" },
            { "byb", "Rublo novo bielo-russo (1994-1999)" },
            { "byr", "Rublo bielo-russo" },
            { "bzd", "D\u00F3lar do Belize" },
            { "cad", "D\u00F3lar canadense" },
            { "cdf", "Franco congol\u00EAs" },
            { "chf", "Franco su\u00ED\u00E7o" },
            { "clf", "Unidades de Fomento chilenas" },
            { "clp", "Peso chileno" },
            { "cny", "Yuan Renminbi chin\u00EAs" },
            { "cop", "Peso colombiano" },
            { "crc", "Colon da Costa Rica" },
            { "csd", "Dinar s\u00E9rvio antigo" },
            { "cuc", "Peso cubano convers\u00EDvel" },
            { "cup", "Peso cubano" },
            { "cve", "Escudo cabo-verdiano" },
            { "cyp", "Libra cipriota" },
            { "czk", "Coroa checa" },
            { "dem", "Marco alem\u00E3o" },
            { "djf", "Franco do Djibuti" },
            { "dkk", "Coroa dinamarquesa" },
            { "dop", "Peso dominicano" },
            { "dzd", "Dinar argelino" },
            { "eek", "Coroa estoniana" },
            { "egp", "Libra eg\u00EDpcia" },
            { "ern", "Nakfa da Eritreia" },
            { "esp", "Peseta espanhola" },
            { "etb", "Birr et\u00EDope" },
            { "fim", "Marca finlandesa" },
            { "fjd", "D\u00F3lar de Fiji" },
            { "fkp", "Libra das Malvinas" },
            { "frf", "Franco franc\u00EAs" },
            { "gbp", "Libra esterlina brit\u00E2nica" },
            { "gel", "Lari georgiano" },
            { "ghc", "Cedi de Gana (1979-2007)" },
            { "ghs", "Cedi gan\u00EAs" },
            { "gip", "Libra de Gibraltar" },
            { "gmd", "Dalasi de G\u00E2mbia" },
            { "gnf", "Franco de Guin\u00E9" },
            { "grd", "Dracma grego" },
            { "gtq", "Quet\u00E7al da Guatemala" },
            { "gwp", "Peso da Guin\u00E9-Bissau" },
            { "gyd", "D\u00F3lar da Guiana" },
            { "hkd", "D\u00F3lar de Hong Kong" },
            { "hnl", "Lempira de Honduras" },
            { "hrk", "Kuna croata" },
            { "htg", "Gurde do Haiti" },
            { "huf", "Forinte h\u00FAngaro" },
            { "idr", "Rupia indon\u00E9sia" },
            { "iep", "Libra irlandesa" },
            { "ils", "Sheqel Novo israelita" },
            { "inr", "R\u00FApia indiana" },
            { "iqd", "Dinar iraquiano" },
            { "irr", "Rial iraniano" },
            { "isk", "Coroa islandesa" },
            { "itl", "Lira italiana" },
            { "jmd", "D\u00F3lar jamaicano" },
            { "jod", "Dinar jordaniano" },
            { "jpy", "Iene japon\u00EAs" },
            { "kes", "Xelim queniano" },
            { "kgs", "Som quirguiz" },
            { "khr", "Riel cambojano" },
            { "kmf", "Franco de Comores" },
            { "kpw", "Won norte-coreano" },
            { "krw", "Won sul-coreano" },
            { "kwd", "Dinar coveitiano" },
            { "kyd", "D\u00F3lar das Ilhas Caiman" },
            { "kzt", "Tenge do Cazaquist\u00E3o" },
            { "lak", "Kip de Laos" },
            { "lbp", "Libra libanesa" },
            { "lkr", "Rupia do Sri Lanka" },
            { "lrd", "D\u00F3lar liberiano" },
            { "lsl", "Loti do Lesoto" },
            { "ltl", "Lita lituano" },
            { "luf", "Franco luxemburgu\u00EAs" },
            { "lvl", "Lats let\u00E3o" },
            { "lyd", "Dinar l\u00EDbio" },
            { "mad", "Dir\u00E9m marroquino" },
            { "mdl", "Leu mold\u00E1vio" },
            { "mga", "Ariary de Madagascar" },
            { "mgf", "Franco de Madagascar" },
            { "mkd", "Dinar maced\u00F4nio" },
            { "mmk", "Kyat de Mianmar" },
            { "mnt", "Tugrik mongol" },
            { "mop", "Pataca macaense" },
            { "mro", "Ouguiya da Maurit\u00E2nia" },
            { "mtl", "Lira maltesa" },
            { "mur", "Rupia de Maur\u00EDcio" },
            { "mvr", "Rupias das Ilhas Maldivas" },
            { "mwk", "Cuacha do Mal\u00E1ui" },
            { "mxn", "Peso mexicano" },
            { "mxv", "Unidade Mexicana de Investimento (UDI)" },
            { "myr", "Ringgit malaio" },
            { "mzm", "Metical antigo de Mo\u00E7ambique" },
            { "mzn", "Metical do Mo\u00E7ambique" },
            { "nad", "D\u00F3lar da Nam\u00EDbia" },
            { "ngn", "Naira nigeriana" },
            { "nio", "C\u00F3rdoba Ouro nicaraguense" },
            { "nlg", "Florim holand\u00EAs" },
            { "nok", "Coroa norueguesa" },
            { "npr", "Rupia nepalesa" },
            { "nzd", "D\u00F3lar da Nova Zel\u00E2ndia" },
            { "omr", "Rial de Om\u00E3" },
            { "pab", "Balboa panamenho" },
            { "pen", "Sol Novo peruano" },
            { "pgk", "Kina da Papua-Nova Guin\u00E9" },
            { "php", "Peso filipino" },
            { "pkr", "Rupia paquistanesa" },
            { "pln", "Zloti polon\u00EAs" },
            { "pte", "Escudo portugu\u00EAs" },
            { "pyg", "Guarani paraguaio" },
            { "qar", "Rial catariano" },
            { "rol", "Leu romeno antigo" },
            { "ron", "Leu romeno" },
            { "rsd", "Dinar s\u00E9rvio" },
            { "rub", "Rublo russo" },
            { "rur", "Rublo russo (1991-1998)" },
            { "rwf", "Franco ruand\u00EAs" },
            { "sar", "Rial saudita" },
            { "sbd", "D\u00F3lar das Ilhas Salom\u00E3o" },
            { "scr", "Rupia das Seychelles" },
            { "sdd", "Dinar sudan\u00EAs" },
            { "sdg", "Libra sudanesa" },
            { "sek", "Coroa sueca" },
            { "sgd", "D\u00F3lar de Cingapura" },
            { "shp", "Libra de Santa Helena" },
            { "sit", "Tolar Bons esloveno" },
            { "skk", "Coroa eslovaca" },
            { "sll", "Leone de Serra Leoa" },
            { "sos", "Xelim somali" },
            { "srd", "D\u00F3lar do Suriname" },
            { "srg", "Florim do Suriname" },
            { "std", "Dobra de S\u00E3o Tom\u00E9 e Pr\u00EDncipe" },
            { "svc", "Colom salvadorenho" },
            { "syp", "Libra s\u00EDria" },
            { "szl", "Lilangeni da Suazil\u00E2ndia" },
            { "thb", "Baht tailand\u00EAs" },
            { "tjs", "Somoni tadjique" },
            { "tmm", "Manat do Turcomenist\u00E3o" },
            { "tmt", "Novo Manat do Turcomenist\u00E3o" },
            { "tnd", "Dinar tunisiano" },
            { "top", "Pa\u02BBanga de Tonga" },
            { "tpe", "Escudo timorense" },
            { "trl", "Lira turca antiga" },
            { "try", "Lira turca" },
            { "ttd", "D\u00F3lar de Trinidad e Tobago" },
            { "twd", "D\u00F3lar Novo de Taiwan" },
            { "tzs", "Xelim da Tanz\u00E2nia" },
            { "uah", "Hryvnia ucraniano" },
            { "ugx", "Xelim ugandense" },
            { "usd", "D\u00F3lar norte-americano" },
            { "usn", "D\u00F3lar norte-americano (Dia seguinte)" },
            { "uss", "D\u00F3lar norte-americano (Mesmo dia)" },
            { "uyu", "Peso uruguaio" },
            { "uzs", "Sum do Usbequist\u00E3o" },
            { "veb", "Bol\u00EDvar venezuelano" },
            { "vef", "Bol\u00EDvar v enezuelano forte" },
            { "vnd", "Dong vietnamita" },
            { "vuv", "Vatu de Vanuatu" },
            { "wst", "Tala samoano" },
            { "xaf", "Franco CFA BEAC" },
            { "xag", "Prata" },
            { "xau", "Ouro" },
            { "xba", "Unidade Composta Europeia" },
            { "xbb", "Unidade Monet\u00E1ria Europeia" },
            { "xbc", "Unidade de Conta Europeia (XBC)" },
            { "xbd", "Unidade de Conta Europeia (XBD)" },
            { "xcd", "D\u00F3lar do Caribe Oriental" },
            { "xdr", "Direitos Especiais de Giro" },
            { "xfo", "Franco-ouro franc\u00EAs" },
            { "xfu", "Franco UIC franc\u00EAs" },
            { "xof", "Franco CFA BCEAO" },
            { "xpd", "Pal\u00E1dio" },
            { "xpf", "Franco CFP" },
            { "xpt", "Platina" },
            { "xts", "C\u00F3digo de Moeda de Teste" },
            { "xxx", "Moeda Desconhecida ou Inv\u00E1lida" },
            { "yer", "Rial iemenita" },
            { "yum", "Dinar noviy iugoslavo" },
            { "zar", "Rand sul-africano" },
            { "zmk", "Cuacha zambiano" },
            { "zwd", "D\u00F3lar do Zimb\u00E1bue" },
            { "zwl", "D\u00F3lar do Zimb\u00E1bue (2009)" },
            { "zwr", "D\u00F3lar do Zimb\u00E1bue (2008)" },
        };
    }
}
