/*
 * Copyright (c) 2012, 2018, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright (C) 1991-2016 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in 
 * http://www.unicode.org/copyright.html.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of the Unicode data files and any associated documentation
 * (the "Data Files") or Unicode software and any associated documentation
 * (the "Software") to deal in the Data Files or Software
 * without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, and/or sell copies of
 * the Data Files or Software, and to permit persons to whom the Data Files
 * or Software are furnished to do so, provided that
 * (a) this copyright and permission notice appear with all copies 
 * of the Data Files or Software,
 * (b) this copyright and permission notice appear in associated 
 * documentation, and
 * (c) there is clear notice in each modified Data File or in the Software
 * as well as in the documentation associated with the Data File(s) or
 * Software that the data or software has been modified.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT OF THIRD PARTY RIGHTS.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
 * NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
 * DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THE DATA FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder
 * shall not be used in advertising or otherwise to promote the sale,
 * use or other dealings in these Data Files or Software without prior
 * written authorization of the copyright holder.
 */

package sun.util.resources.cldr.ext;

import sun.util.resources.OpenListResourceBundle;

public class CurrencyNames_it extends OpenListResourceBundle {
    @Override
    protected final Object[][] getContents() {
        final String metaValue_CNH = "CNH";
        final Object[][] data = new Object[][] {
            { "mwk", "kwacha malawiano" },
            { "FJD", "FJD" },
            { "MXN", "MXN" },
            { "lul", "franco finanziario del Lussemburgo" },
            { "LVL", "LVL" },
            { "SCR", "SCR" },
            { "CDF", "CDF" },
            { "bad", "dinar Bosnia-Herzegovina" },
            { "BBD", "BBD" },
            { "HNL", "HNL" },
            { "UGX", "UGX" },
            { "fim", "markka finlandese" },
            { "dem", "marco tedesco" },
            { "bam", "marco convertibile della Bosnia-Herzegovina" },
            { "egp", "sterlina egiziana" },
            { "SDG", "SDG" },
            { "nzd", "dollaro neozelandese" },
            { "IQD", "IQD" },
            { "GMD", "GMD" },
            { "ugs", "scellino ugandese (1966\u20131987)" },
            { "fjd", "dollaro delle Figi" },
            { "mxn", "peso messicano" },
            { "lvl", "lats lettone" },
            { "scr", "rupia delle Seychelles" },
            { "cdf", "franco congolese" },
            { "mxp", "peso messicano d\u2019argento (1861\u20131992)" },
            { "bbd", "dollaro di Barbados" },
            { "MYR", "MYR" },
            { "hnl", "lempira honduregna" },
            { "ugx", "scellino ugandese" },
            { "lvr", "rublo lettone" },
            { "FKP", "FKP" },
            { "mxv", "unidad de inversion (UDI) messicana" },
            { "sdd", "dinaro sudanese" },
            { "sdg", "sterlina sudanese" },
            { "zrn", "nuovo zaire dello Zaire" },
            { "SEK", "SEK" },
            { "iqd", "dinaro iracheno" },
            { "GNF", "GNF" },
            { "gmd", "dalasi gambiano" },
            { "MZN", "MZN" },
            { "QAR", "QAR" },
            { "zrz", "zaire dello Zaire" },
            { "myr", "ringgit malese" },
            { "IRR", "IRR" },
            { "fkp", "sterlina delle Falkland" },
            { "xof", "franco CFA BCEAO" },
            { "THB", "\u0e3f" },
            { "BDT", "BDT" },
            { "LYD", "LYD" },
            { "sek", "corona svedese" },
            { "KWD", "KWD" },
            { "mze", "escudo del Mozambico" },
            { "gnf", "franco della Guinea" },
            { "ISK", "ISK" },
            { "mzn", "metical mozambicano" },
            { "qar", "rial qatariano" },
            { "irr", "rial iraniano" },
            { "gns", "syli della Guinea" },
            { "xpd", "palladio" },
            { "thb", "baht thailandese" },
            { "xpf", "franco CFP" },
            { "PAB", "PAB" },
            { "SGD", "SGD" },
            { "bdt", "taka bangladese" },
            { "lyd", "dinaro libico" },
            { "kwd", "dinaro kuwaitiano" },
            { "xpt", "platino" },
            { "CHF", "CHF" },
            { "HRK", "HRK" },
            { "isk", "corona islandese" },
            { "DJF", "DJF" },
            { "bec", "franco belga (convertibile)" },
            { "bef", "franco belga" },
            { "bel", "franco belga (finanziario)" },
            { "pab", "balboa panamense" },
            { "sgd", "dollaro di Singapore" },
            { "KYD", "KYD" },
            { "SHP", "SHP" },
            { "hrd", "dinaro croato" },
            { "TJS", "TJS" },
            { "AED", "AED" },
            { "chf", "franco svizzero" },
            { "hrk", "kuna croata" },
            { "itl", "lira italiana" },
            { "djf", "franco di Gibuti" },
            { "DKK", "DKK" },
            { "BGN", "BGN" },
            { "xre", "fondi RINET" },
            { "adp", "peseta andorrana" },
            { "vnd", "dong vietnamita" },
            { "kyd", "dollaro delle Isole Cayman" },
            { "HTG", "HTG" },
            { "gqe", "ekwele della Guinea Equatoriale" },
            { "shp", "sterlina di Sant\u2019Elena" },
            { "tjs", "somoni tagiko" },
            { "tjr", "rublo del Tajikistan" },
            { "BHD", "BHD" },
            { "aed", "dirham degli Emirati Arabi Uniti" },
            { "KZT", "KZT" },
            { "dkk", "corona danese" },
            { "bgl", "lev bulgaro (1962\u20131999)" },
            { "zwd", "dollaro dello Zimbabwe" },
            { "bgn", "lev bulgaro" },
            { "AFN", "AFN" },
            { "yud", "dinaro forte yugoslavo" },
            { "zwl", "dollaro zimbabwiano (2009)" },
            { "yum", "dinaro noviy yugoslavo" },
            { "yun", "dinaro convertibile yugoslavo" },
            { "HUF", "HUF" },
            { "grd", "dracma greca" },
            { "htg", "gourde haitiano" },
            { "afa", "afgani (1927\u20132002)" },
            { "BIF", "BIF" },
            { "bhd", "dinaro del Bahrein" },
            { "sit", "tallero sloveno" },
            { "kzt", "tenge kazako" },
            { "afn", "afghani" },
            { "rhd", "dollaro della Rhodesia" },
            { "NAD", "NAD" },
            { "xts", "codice di verifica della valuta" },
            { "PEN", "PEN" },
            { "huf", "fiorino ungherese" },
            { "WST", "WST" },
            { "TMT", "TMT" },
            { "bif", "franco del Burundi" },
            { "GTQ", "GTQ" },
            { "CLP", "CLP" },
            { "TND", "TND" },
            { "nad", "dollaro namibiano" },
            { "SLL", "SLL" },
            { "skk", "corona slovacca" },
            { "pei", "inti peruviano" },
            { "tmm", "manat turkmeno (1993\u20132009)" },
            { "pen", "sol peruviano" },
            { "wst", "tala samoano" },
            { "tmt", "manat turkmeno" },
            { "frf", "franco francese" },
            { "clf", "unidades de fomento chilene" },
            { "pes", "sol peruviano (1863\u20131965)" },
            { "DOP", "DOP" },
            { "gtq", "quetzal guatemalteco" },
            { "clp", "peso cileno" },
            { "tnd", "dinaro tunisino" },
            { "MAD", "MAD" },
            { "sll", "leone della Sierra Leone" },
            { "TOP", "TOP" },
            { "PGK", "PGK" },
            { "CNH", metaValue_CNH },
            { "ERN", "ERN" },
            { "dop", "peso dominicano" },
            { "mad", "dirham marocchino" },
            { "maf", "franco marocchino" },
            { "top", "pa\u02bbanga tongano" },
            { "pgk", "kina papuana" },
            { "BMD", "BMD" },
            { "PHP", "PHP" },
            { "cnh", metaValue_CNH },
            { "ern", "nakfa eritreo" },
            { "COP", "COP" },
            { "USD", "USD" },
            { "tpe", "escudo di Timor" },
            { "cny", "renminbi cinese" },
            { "ETB", "ETB" },
            { "esa", "peseta spagnola account" },
            { "gwe", "escudo della Guinea portoghese" },
            { "esb", "peseta spagnola account convertibile" },
            { "SOS", "SOS" },
            { "VUV", "VUV" },
            { "LAK", "LAK" },
            { "bmd", "dollaro delle Bermuda" },
            { "BND", "BND" },
            { "php", "peso filippino" },
            { "xxx", "valuta sconosciuta" },
            { "ALL", "ALL" },
            { "gwp", "peso della Guinea-Bissau" },
            { "esp", "peseta spagnola" },
            { "cop", "peso colombiano" },
            { "usd", "dollaro statunitense" },
            { "usn", "dollaro statunitense (next day)" },
            { "etb", "birr etiope" },
            { "GYD", "GYD" },
            { "BOB", "BOB" },
            { "MDL", "MDL" },
            { "uss", "dollaro statunitense (same day)" },
            { "sos", "scellino somalo" },
            { "vuv", "vatu di Vanuatu" },
            { "lak", "kip laotiano" },
            { "AMD", "AMD" },
            { "bnd", "dollaro del Brunei" },
            { "TRY", "TRY" },
            { "LBP", "LBP" },
            { "all", "lek albanese" },
            { "trl", "lira turca (1922\u20132005)" },
            { "RON", "RON" },
            { "gyd", "dollaro della Guyana" },
            { "NGN", "NGN" },
            { "bob", "boliviano" },
            { "mdl", "leu moldavo" },
            { "CRC", "CRC" },
            { "PKR", "PKR" },
            { "amd", "dram armeno" },
            { "ANG", "ANG" },
            { "try", "lira turca" },
            { "lbp", "lira libanese" },
            { "bop", "peso boliviano" },
            { "eur", "euro" },
            { "SRD", "SRD" },
            { "TTD", "TTD" },
            { "bov", "mvdol boliviano" },
            { "rol", "leu della Romania" },
            { "ron", "leu rumeno" },
            { "AOA", "AOA" },
            { "PLN", "PLN" },
            { "ngn", "naira nigeriana" },
            { "crc", "col\u00f3n costaricano" },
            { "pkr", "rupia pakistana" },
            { "ang", "fiorino delle Antille olandesi" },
            { "srd", "dollaro del Suriname" },
            { "ttd", "dollaro di Trinidad e Tobago" },
            { "MGA", "MGA" },
            { "srg", "fiorino del Suriname" },
            { "SSP", "SSP" },
            { "aoa", "kwanza angolano" },
            { "pln", "z\u0142oty polacco" },
            { "NIO", "NIO" },
            { "csd", "antico dinaro serbo" },
            { "csk", "corona forte cecoslovacca" },
            { "aok", "kwanza angolano (1977\u20131990)" },
            { "BRL", "BRL" },
            { "plz", "z\u0142oty Polacco (1950\u20131995)" },
            { "aon", "nuovo kwanza angolano (1990\u20132000)" },
            { "STD", "STD" },
            { "aor", "kwanza reajustado angolano (1995\u20131999)" },
            { "mga", "ariary malgascio" },
            { "nic", "cordoba nicaraguense" },
            { "ZAR", "ZAR" },
            { "STN", "STN" },
            { "mgf", "franco malgascio" },
            { "CUC", "CUC" },
            { "ssp", "sterlina sud-sudanese" },
            { "BSD", "BSD" },
            { "brc", "cruzado brasiliano" },
            { "brb", "cruzeiro novo brasiliano (1967\u20131986)" },
            { "bre", "cruzeiro brasiliano (1990\u20131993)" },
            { "nio", "c\u00f3rdoba nicaraguense" },
            { "brl", "real brasiliano" },
            { "CUP", "CUP" },
            { "brn", "cruzado novo brasiliano" },
            { "TWD", "TWD" },
            { "RSD", "RSD" },
            { "std", "dobra di Sao Tom\u00e9 e Principe (1977\u20132017)" },
            { "brr", "cruzeiro brasiliano" },
            { "zal", "rand sudafricano (finanziario)" },
            { "zar", "rand sudafricano" },
            { "stn", "dobra di Sao Tom\u00e9 e Principe" },
            { "UYU", "UYU" },
            { "cuc", "peso cubano convertibile" },
            { "bsd", "dollaro delle Bahamas" },
            { "CVE", "CVE" },
            { "OMR", "OMR" },
            { "KES", "KES" },
            { "BTN", "BTN" },
            { "cup", "peso cubano" },
            { "twd", "nuovo dollaro taiwanese" },
            { "ARS", "ARS" },
            { "rsd", "dinaro serbo" },
            { "uyi", "peso uruguaiano in unit\u00e0 indicizzate" },
            { "uyp", "peso uruguaiano (1975\u20131993)" },
            { "UZS", "UZS" },
            { "uyu", "peso uruguayano" },
            { "ara", "austral argentino" },
            { "sur", "rublo sovietico" },
            { "cve", "escudo capoverdiano" },
            { "omr", "rial omanita" },
            { "kes", "scellino keniota" },
            { "btn", "ngultrum bhutanese" },
            { "RUB", "RUB" },
            { "arp", "peso argentino (vecchio Cod.)" },
            { "svc", "col\u00f3n salvadoregno" },
            { "ars", "peso argentino" },
            { "MKD", "MKD" },
            { "nlg", "fiorino olandese" },
            { "DZD", "DZD" },
            { "uzs", "sum uzbeco" },
            { "KGS", "KGS" },
            { "buk", "kyat birmano" },
            { "rub", "rublo russo" },
            { "mkd", "denar macedone" },
            { "TZS", "TZS" },
            { "rur", "rublo della CSI" },
            { "dzd", "dinaro algerino" },
            { "KHR", "KHR" },
            { "IDR", "IDR" },
            { "kgs", "som kirghiso" },
            { "BWP", "BWP" },
            { "xaf", "franco CFA BEAC" },
            { "xag", "argento" },
            { "RWF", "RWF" },
            { "ats", "scellino austriaco" },
            { "mlf", "franco di Mali" },
            { "MMK", "MMK" },
            { "NOK", "NOK" },
            { "SYP", "SYP" },
            { "tzs", "scellino della Tanzania" },
            { "xau", "oro" },
            { "aud", "dollaro australiano" },
            { "LKR", "LKR" },
            { "khr", "riel cambogiano" },
            { "CZK", "CZK" },
            { "idr", "rupia indonesiana" },
            { "xba", "unit\u00e0 composita europea" },
            { "xbc", "unit\u00e0 di acconto europea (XBC)" },
            { "ydd", "dinaro dello Yemen" },
            { "xbb", "unit\u00e0 monetaria europea" },
            { "bwp", "pula del Botswana" },
            { "cyp", "sterlina cipriota" },
            { "xbd", "unit\u00e0 di acconto europea (XBD)" },
            { "rwf", "franco ruandese" },
            { "SZL", "SZL" },
            { "YER", "YER" },
            { "mmk", "kyat di Myanmar" },
            { "nok", "corona norvegese" },
            { "syp", "lira siriana" },
            { "AWG", "AWG" },
            { "NPR", "NPR" },
            { "MNT", "MNT" },
            { "lkr", "rupia di Sri Lanka" },
            { "czk", "corona ceca" },
            { "iep", "sterlina irlandese" },
            { "BYN", "BYN" },
            { "xcd", "dollaro dei Caraibi orientali" },
            { "BYR", "BYR" },
            { "pte", "escudo portoghese" },
            { "szl", "lilangeni dello Swaziland" },
            { "yer", "riyal yemenita" },
            { "byb", "nuovo rublo bielorusso (1994\u20131999)" },
            { "BZD", "BZD" },
            { "MOP", "MOP" },
            { "awg", "fiorino di Aruba" },
            { "npr", "rupia nepalese" },
            { "mnt", "tugrik mongolo" },
            { "gbp", "sterlina britannica" },
            { "byn", "rublo bielorusso" },
            { "byr", "rublo bielorusso (2000\u20132016)" },
            { "xdr", "diritti speciali di incasso" },
            { "bzd", "dollaro del Belize" },
            { "mop", "pataca di Macao" },
            { "KMF", "KMF" },
            { "GEL", "GEL" },
            { "AZN", "AZN" },
            { "UAH", "UAH" },
            { "xfo", "franco oro francese" },
            { "kmf", "franco comoriano" },
            { "xfu", "franco UIC francese" },
            { "MRO", "MRO" },
            { "gek", "kupon larit georgiano" },
            { "gel", "lari georgiano" },
            { "azn", "manat azero" },
            { "azm", "manat azero (1993\u20132006)" },
            { "uah", "grivnia ucraina" },
            { "uak", "karbovanetz ucraino" },
            { "PYG", "PYG" },
            { "JMD", "JMD" },
            { "mro", "ouguiya della Mauritania (1973\u20132017)" },
            { "mru", "ouguiya della Mauritania" },
            { "VEF", "VEF" },
            { "LRD", "LRD" },
            { "pyg", "guaran\u00ed paraguayano" },
            { "jmd", "dollaro giamaicano" },
            { "ZMW", "ZMW" },
            { "veb", "bolivar venezuelano (1871\u20132008)" },
            { "GHS", "GHS" },
            { "KPW", "KPW" },
            { "ecs", "sucre dell\u2019Ecuador" },
            { "vef", "bol\u00edvar venezuelano" },
            { "ecv", "unidad de valor constante (UVC) dell\u2019Ecuador" },
            { "zmk", "kwacha dello Zambia (1968\u20132012)" },
            { "JOD", "JOD" },
            { "lrd", "dollaro liberiano" },
            { "HKD", "HKD" },
            { "ghc", "cedi del Ghana" },
            { "mtl", "lira maltese" },
            { "zmw", "kwacha dello Zambia" },
            { "mtp", "sterlina maltese" },
            { "MUR", "MUR" },
            { "ilp", "sterlina israeliana" },
            { "GIP", "GIP" },
            { "ils", "nuovo siclo israeliano" },
            { "ghs", "cedi ghanese" },
            { "kpw", "won nordcoreano" },
            { "jod", "dinaro giordano" },
            { "hkd", "dollaro di Hong Kong" },
            { "lsl", "loti del Lesotho" },
            { "LTL", "LTL" },
            { "SAR", "SAR" },
            { "cad", "dollaro canadese" },
            { "MVR", "MVR" },
            { "eek", "corona dell\u2019Estonia" },
            { "mur", "rupia mauriziana" },
            { "gip", "sterlina di Gibilterra" },
            { "KRW", "KRW" },
            { "JPY", "JPY" },
            { "SBD", "SBD" },
            { "MWK", "MWK" },
            { "ltl", "litas lituano" },
            { "sar", "riyal saudita" },
            { "mvr", "rufiyaa delle Maldive" },
            { "ddm", "ostmark della Germania Orientale" },
            { "inr", "rupia indiana" },
            { "ltt", "talonas lituani" },
            { "BAM", "BAM" },
            { "EGP", "EGP" },
            { "krw", "won sudcoreano" },
            { "jpy", "yen giapponese" },
            { "sbd", "dollaro delle Isole Salomone" },
            { "luc", "franco convertibile del Lussemburgo" },
            { "luf", "franco del Lussemburgo" },
        };
        return data;
    }
}
