package sun.print.resources;

import java.util.ListResourceBundle;

public final class serviceui extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "Automatic-Feeder", "Automatic Feeder" },
            { "Cassette", "Cassette" },
            { "Form-Source", "Form Source" },
            { "Large-Format", "Large Format" },
            { "Manual-Envelope", "Manual Envelope" },
            { "Small-Format", "Small Format" },
            { "Tractor-Feeder", "Tractor Feeder" },
            { "a", "Engineering A" },
            { "accepting-jobs", "Accepting jobs" },
            { "auto-select", "Automatically Select" },
            { "b", "Engineering B" },
            { "border.chromaticity", "Color Appearance" },
            { "border.copies", "Copies" },
            { "border.jobattributes", "Job Attributes" },
            { "border.margins", "Margins" },
            { "border.media", "Media" },
            { "border.orientation", "Orientation" },
            { "border.printrange", "Print Range" },
            { "border.printservice", "Print Service" },
            { "border.quality", "Quality" },
            { "border.sides", "Sides" },
            { "bottom", "Bottom" },
            { "button.cancel", "Cancel" },
            { "button.ok", "OK" },
            { "button.print", "Print" },
            { "button.properties", "P&roperties..." },
            { "c", "Engineering C" },
            { "checkbox.collate", "&Collate" },
            { "checkbox.jobsheets", "&Banner Page" },
            { "checkbox.printtofile", "Print To &File" },
            { "d", "Engineering D" },
            { "dialog.noprintermsg", "No print service found." },
            { "dialog.overwrite", "This file already exists.  Would you like to overwrite the existing file?" },
            { "dialog.owtitle", "Print To File" },
            { "dialog.printtitle", "Print" },
            { "dialog.printtofile", "Print To File" },
            { "dialog.pstitle", "Page Setup" },
            { "dialog.writeerror", "Cannot write to file:" },
            { "e", "Engineering E" },
            { "envelope", "Envelope" },
            { "error.destination", "Invalid filename; please try again" },
            { "error.pagerange", "Invalid page range; please re-enter values (e.g. 1-3,5,7-10)" },
            { "executive", "Executive" },
            { "folio", "Folio" },
            { "invite-envelope", "Invitation Envelope" },
            { "invoice", "Invoice" },
            { "iso-2a0", "2A0 (ISO/DIN & JIS)" },
            { "iso-4a0", "4A0 (ISO/DIN & JIS)" },
            { "iso-a0", "A0 (ISO/DIN & JIS)" },
            { "iso-a1", "A1 (ISO/DIN & JIS)" },
            { "iso-a10", "A10 (ISO/DIN & JIS)" },
            { "iso-a2", "A2 (ISO/DIN & JIS)" },
            { "iso-a3", "A3 (ISO/DIN & JIS)" },
            { "iso-a4", "A4 (ISO/DIN & JIS)" },
            { "iso-a5", "A5 (ISO/DIN & JIS)" },
            { "iso-a6", "A6 (ISO/DIN & JIS)" },
            { "iso-a7", "A7 (ISO/DIN & JIS)" },
            { "iso-a8", "A8 (ISO/DIN & JIS)" },
            { "iso-a9", "A9 (ISO/DIN & JIS)" },
            { "iso-b0", "B0 (ISO/DIN)" },
            { "iso-b1", "B1 (ISO/DIN)" },
            { "iso-b10", "B10 (ISO/DIN)" },
            { "iso-b2", "B2 (ISO/DIN)" },
            { "iso-b3", "B3 (ISO/DIN)" },
            { "iso-b4", "B4 (ISO/DIN)" },
            { "iso-b5", "B5 (ISO/DIN)" },
            { "iso-b6", "B6 (ISO/DIN)" },
            { "iso-b7", "B7 (ISO/DIN)" },
            { "iso-b8", "B8 (ISO/DIN)" },
            { "iso-b9", "B9 (ISO/DIN)" },
            { "iso-c0", "C0 (ISO/DIN)" },
            { "iso-c1", "C1 (ISO/DIN)" },
            { "iso-c10", "C10 (ISO/DIN)" },
            { "iso-c2", "C2 (ISO/DIN)" },
            { "iso-c3", "C3 (ISO/DIN)" },
            { "iso-c4", "C4 (ISO/DIN)" },
            { "iso-c5", "C5 (ISO/DIN)" },
            { "iso-c6", "C6 (ISO/DIN)" },
            { "iso-c7", "C7 (ISO/DIN)" },
            { "iso-c8", "C8 (ISO/DIN)" },
            { "iso-c9", "C9 (ISO/DIN)" },
            { "iso-designated-long", "ISO Designated Long" },
            { "italian-envelope", "Italy Envelope" },
            { "italy-envelope", "Italy Envelope" },
            { "japanese-postcard", "Postcard (JIS)" },
            { "jis-b0", "B0 (JIS)" },
            { "jis-b1", "B1 (JIS)" },
            { "jis-b10", "B10 (JIS)" },
            { "jis-b2", "B2 (JIS)" },
            { "jis-b3", "B3 (JIS)" },
            { "jis-b4", "B4 (JIS)" },
            { "jis-b5", "B5 (JIS)" },
            { "jis-b6", "B6 (JIS)" },
            { "jis-b7", "B7 (JIS)" },
            { "jis-b8", "B8 (JIS)" },
            { "jis-b9", "B9 (JIS)" },
            { "label.bottommargin", "&bottom" },
            { "label.inches", "(in)" },
            { "label.info", "Info:" },
            { "label.jobname", "&Job Name:" },
            { "label.leftmargin", "le&ft" },
            { "label.millimetres", "(mm)" },
            { "label.numcopies", "Number &of copies:" },
            { "label.priority", "P&riority:" },
            { "label.psname", "&Name:" },
            { "label.pstype", "Type:" },
            { "label.rangeto", "To" },
            { "label.rightmargin", "&right" },
            { "label.size", "Si&ze:" },
            { "label.source", "Sour&ce:" },
            { "label.status", "Status:" },
            { "label.topmargin", "&top" },
            { "label.username", "&User Name:" },
            { "large-capacity", "Large Capacity" },
            { "ledger", "Ledger" },
            { "main", "Main" },
            { "manual", "Manual" },
            { "middle", "Middle" },
            { "monarch-envelope", "Monarch Envelope" },
            { "na-10x13-envelope", "10x15 Envelope" },
            { "na-10x14-envelope", "10x15 Envelope" },
            { "na-10x15-envelope", "10x15 Envelope" },
            { "na-5x7", "5\" x 7\" Paper" },
            { "na-6x9-envelope", "6x9 Envelope" },
            { "na-7x9-envelope", "6x7 Envelope" },
            { "na-8x10", "8\" x 10\" Paper" },
            { "na-9x11-envelope", "9x11 Envelope" },
            { "na-9x12-envelope", "9x12 Envelope" },
            { "na-legal", "Legal" },
            { "na-letter", "Letter" },
            { "na-number-10-envelope", "No. 10 Envelope" },
            { "na-number-11-envelope", "No. 11 Envelope" },
            { "na-number-12-envelope", "No. 12 Envelope" },
            { "na-number-14-envelope", "No. 14 Envelope" },
            { "na-number-9-envelope", "No. 9 Envelope" },
            { "not-accepting-jobs", "Not accepting jobs" },
            { "oufuko-postcard", "Double Postcard (JIS)" },
            { "personal-envelope", "Personal Envelope" },
            { "quarto", "Quarto" },
            { "radiobutton.color", "&Color" },
            { "radiobutton.draftq", "Dra&ft" },
            { "radiobutton.duplex", "&Duplex" },
            { "radiobutton.highq", "&High" },
            { "radiobutton.landscape", "&Landscape" },
            { "radiobutton.monochrome", "&Monochrome" },
            { "radiobutton.normalq", "&Normal" },
            { "radiobutton.oneside", "&One Side" },
            { "radiobutton.portrait", "&Portrait" },
            { "radiobutton.rangeall", "A&ll" },
            { "radiobutton.rangepages", "Pag&es" },
            { "radiobutton.revlandscape", "Reverse La&ndscape" },
            { "radiobutton.revportrait", "Reverse Portra&it" },
            { "radiobutton.tumble", "&Tumble" },
            { "side", "Side" },
            { "tab.appearance", "&Appearance" },
            { "tab.general", "&General" },
            { "tab.pagesetup", "Page &Setup" },
            { "tabloid", "Tabloid" },
            { "top", "Top" },
        };
    }
}
