package com.sun.accessibility.internal.resources;

import java.util.ListResourceBundle;

public final class accessibility_en extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "active", "active" },
            { "alert", "alert" },
            { "armed", "armed" },
            { "awtcomponent", "AWT component" },
            { "busy", "busy" },
            { "canvas", "canvas" },
            { "checkbox", "check box" },
            { "checked", "checked" },
            { "childNodeOf", "child node of" },
            { "collapsed", "collapsed" },
            { "colorchooser", "color chooser" },
            { "columnheader", "column header" },
            { "combobox", "combo box" },
            { "controlledBy", "controlledBy" },
            { "controllerFor", "controllerFor" },
            { "desktopicon", "desktop icon" },
            { "desktoppane", "desktop pane" },
            { "dialog", "dialog" },
            { "directorypane", "directory pane" },
            { "editable", "editable" },
            { "editbar", "editbar" },
            { "embeddedBy", "embedded by" },
            { "embeds", "embeds" },
            { "enabled", "enabled" },
            { "expandable", "expandable" },
            { "expanded", "expanded" },
            { "filechooser", "file chooser" },
            { "filler", "filler" },
            { "flowsFrom", "flows from" },
            { "flowsTo", "flows to" },
            { "focusable", "focusable" },
            { "focused", "focused" },
            { "footer", "footer" },
            { "frame", "frame" },
            { "glasspane", "glass pane" },
            { "header", "header" },
            { "horizontal", "horizontal" },
            { "htmlcontainer", "HTML container" },
            { "iconified", "iconified" },
            { "indeterminate", "indeterminate" },
            { "internalframe", "internal frame" },
            { "label", "label" },
            { "labelFor", "label for" },
            { "labeledBy", "labeled by" },
            { "layeredpane", "layered pane" },
            { "list", "list" },
            { "listitem", "list item" },
            { "managesDescendants", "manages descendants" },
            { "memberOf", "member of" },
            { "menu", "menu" },
            { "menubar", "menu bar" },
            { "menuitem", "menu item" },
            { "modal", "modal" },
            { "multiline", "multiple line" },
            { "multiselectable", "multiselectable" },
            { "opaque", "opaque" },
            { "optionpane", "option pane" },
            { "pagetab", "page tab" },
            { "pagetablist", "page tab list" },
            { "panel", "panel" },
            { "paragraph", "paragraph" },
            { "parentWindowOf", "parent window of" },
            { "passwordtext", "password text" },
            { "popupmenu", "popup menu" },
            { "pressed", "pressed" },
            { "progressMonitor", "progress monitor" },
            { "progressbar", "progress bar" },
            { "pushbutton", "push button" },
            { "radiobutton", "radio button" },
            { "resizable", "resizable" },
            { "rootpane", "root pane" },
            { "rowheader", "row header" },
            { "ruler", "ruler" },
            { "scrollbar", "scroll bar" },
            { "scrollpane", "scroll pane" },
            { "selectable", "selectable" },
            { "selected", "selected" },
            { "separator", "separator" },
            { "showing", "showing" },
            { "singleline", "single line" },
            { "slider", "slider" },
            { "splitpane", "split pane" },
            { "subwindowOf", "subwindow of" },
            { "swingcomponent", "swing component" },
            { "table", "table" },
            { "text", "text" },
            { "togglebutton", "toggle button" },
            { "toolbar", "tool bar" },
            { "tooltip", "tool tip" },
            { "transient", "transient" },
            { "tree", "tree" },
            { "truncated", "truncated" },
            { "unknown", "unknown" },
            { "vertical", "vertical" },
            { "viewport", "viewport" },
            { "visible", "visible" },
            { "window", "window" },
        };
    }
}
